### ISSUE TITLE
tracking issue for kubeadm init phases

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1163]
this tracking issue **goes outside of the scope for 1.13** AKA we have items for post 1.13.

this post will summarize the work that has to be done to graduate the kubeadm phases to beta (ga?).
the issue will track PRs, assignees, but also have extra actions that have to be handled.
if you wish to work on a certain item please add a comment about it.

discussion happened around this gdoc in the 17oct/2018 kubeadm office hours meeting:
https://docs.google.com/document/d/10ZQ5erWhab3GJH-CjCBT6NgvLJQygyqPkQUsx_y5snQ/edit?usp=sharing

notes:
- we are keeping the `kubeadm alpha` command for now, but moving all viable phases in the bellow list to `kubeadm init phase`
- some phases are going to be collapsed into a parent phase, but optionally sub-phases to be exposed over time.
- some phases are shuffled around or removed.
- we have plans to support aliases where a sub-phase can call the same code as another sub-phase.
- some phases are going to be hidden which implies that they are going to be called by the backend in a specific order, but the user would not be able to call them from CLI or skip them.

### list of phases (ordered)
---
- [x] preflight
- assigned: @fabriziopandini 
- PR: https://github.com/kubernetes/kubernetes/pull/69666
**NOTE:** this PR also serves as an example of how a new phases should be graduated.

- [x] kubelet-start
- assigned: @fabriziopandini
- PR: https://github.com/kubernetes/kubernetes/pull/70049

currently this phase has sub-phases, the idea is to collapse them into a single phase. shuffle folders around etc. this however removes the control if the user wants to write a kubelet config, modify it and then start. so we might want to expose it eventually based on user feedback.

- [x] certs
- assigned: @ereslibre 
- PR: https://github.com/kubernetes/kubernetes/pull/70331

should be a straight forward one, move all cert sub commands as sub phases.
`renew` needs to not be a sub-phase of certs, extra item bellow.

- [x] kubeconfig
- assigned: @fabriziopandini 
- PR: https://github.com/kubernetes/kubernetes/pull/70098

same as certs,
`user` however should be kept as an utility under `kubeadm alpha kubeconfig user` and not being a phase.

- [x] control-plane
- assigned: @neolit123 
- PR: https://github.com/kubernetes/kubernetes/pull/70097

contains sub-phases for the control plane components. under api-server we also need to handle audit-policy (currently feature gated as a separate phase). there are plans to add aliases for certs here and eventually also have sub-sub-commands under each control plane component to 1) write config 2) write cert

- [x] etcd
- assigned: @neolit123 
- PR: https://github.com/kubernetes/kubernetes/pull/70388

similar to control-plane, optionally enable 1) write config 2) write cert as sub phases here eventually too.

- [x] wait-control-plane
- assigned: @neolit123 
- PR: https://github.com/kubernetes/kubernetes/pull/70512

[hidden phase!](https://github.com/kubernetes/kubernetes/blob/4f26d1de5f45a16eb113e9e5e1a9766dad70f6a7/cmd/kubeadm/app/cmd/init.go#L475-L501)

- [x] upload-config
- assigned: @yagonobre 
- PR: https://github.com/kubernetes/kubernetes/pull/70405

this should including uploading the kubelet config (currently under kubelet phase) and the kubeadm config. both should be exposed as sub-phases.

[annotate-cri-socket]((https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/init.go#L524-L527)) should be part of `uploading the kubelet config `

- [x] mark-control-plane
- assigned: @RA489 @neolit123 
- PR: https://github.com/kubernetes/kubernetes/pull/70885

renamed from mark-master.

- [x] bootstrap-token
- assigned: @yagonobre 
- PR: https://github.com/kubernetes/kubernetes/pull/70727

should contain all of these, but collapsed and not exposed as sub-phases.
```
create (the function is CreateOrUpdate...)
allow-post-rbac-csr
auto-approve-node-tokens
auto-approve-node-cert-rotation
create-bootstrap-config-map 
create-cluster-info-rbac
```

- [x] addons
- assigned: @yagonobre 
- PR: https://github.com/kubernetes/kubernetes/pull/70354

should contain dns and proxy as subphases exposed in that order.

---

### other action items:

- [x] printing the join command should happen after all the phases in init have finished
- assigned: @yuexiao-wang
- PR: https://github.com/kubernetes/kubernetes/pull/70795

this needs to handle the case where the creation of a token was skipped.

- [x] `alpha phase certs renew` should be moved to `alpha certs renew` (not a phase)
- assigned: @fabriziopandini 
- PR: https://github.com/kubernetes/kubernetes/pull/70333

- [ ] app/phases/upgrade needs to be moved to generic kubeadm utils (not a phase)
- assigned: @yuexiao-wang 
- PR: https://github.com/kubernetes/kubernetes/pull/70346

- [x]  certs/pkiutil needs to be moved to generic kubeadm utils (not a phase)
- assigned: @yuexiao-wang 
- PR: https://github.com/kubernetes/kubernetes/pull/70336

- [ ] bootstraptoken/node/token.go the utils in here need to be moved outside of k/k 
- assigned: @neolit123 
- PR: https://github.com/kubernetes/kubernetes/pull/69979

- [x] enable-dynamic-kubelet-config should be moved outside of phases
- assigned: @yagonobre
- PR: https://github.com/kubernetes/kubernetes/pull/70849

it's feature gated.

to be decided....
the new home for this should be "k8s.io/cluster-bootstrap/token/util"
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cluster-bootstrap/token/util/helpers.go

**Comment by timothysc** [comment]
This looks good, but I think we might want to change some of the names, and obviously move selfhosting into it's own space.

**Comment by fabriziopandini** [comment]
@neolit123 could you kindly change this issues into a tracking issue /help-wanted that we can use to assign part of this effort to volunteers... 

I think that @ereslibre, @RA489, @Klaven can help on this effort once the PR with the first phase implementation merges; ideally who takes in charge a phase should implement related subphases as well

**Comment by neolit123** [comment]
@fabriziopandini 
done.

**Comment by neolit123** [comment]
are we going to discuss the list of phases this wekks kubeadm office hour?. we need a solid list...

**Comment by neolit123** [comment]
now that we have the list of phases i will update this tracking issue tomorrow.

**Comment by fabriziopandini** [comment]
@neolit123 thanks for this write-up. It is great starting point
@ereslibre, @RA489, @Klaven time for volunteering!

**Comment by neolit123** [comment]
a couple of requests for volunteers :)
- please, don't mention this issue in commit messages, because it will spam it on commit rebases.
- in PR descriptions use, `Ref #this-issue` instead of `Fixes #this-issue-num`, so that we don't close it on merge.

thanks.

**Comment by neolit123** [comment]
@fabriziopandini 
btw i'm not exactly sure how we can sync the work here, unless phases are implemented in the presented order. the code in runInit() would still have to be present and we have to hold PRs that implement say mark-control-plane in the new fashion. otherwise we are going to break master.

**Comment by fabriziopandini** [comment]
@neolit123 I'm confident we can sync via slack/this issue

BTW, I'm taking phase kubelet-start

**Comment by fabriziopandini** [comment]
taking kubeconfig

**Comment by neolit123** [comment]
taking control-plane but really want the PR that removes placeholder docs merged...

**Comment by neolit123** [comment]
taking etcd

**Comment by yuexiao-wang** [comment]
taking certs/pkiutil

**Comment by ereslibre** [comment]
@fabriziopandini @neolit123 Started https://github.com/kubernetes/kubernetes/pull/70331, still in `WIP`, but you can modify the comment linking to this PR, thanks!

**Comment by yuexiao-wang** [comment]
@neolit123 my task has done in https://github.com/kubernetes/kubernetes/pull/70336.
where is certs/upgrade which i cannot find?

**Comment by neolit123** [comment]
@yuexiao-wang 

>  my task has done in kubernetes/kubernetes#70336.

will review it next week. thanks.

> where is certs/upgrade which i cannot find?

https://github.com/kubernetes/kubernetes/tree/master/cmd/kubeadm/app/phases/upgrade

**Comment by yuexiao-wang** [comment]
@neolit123 thanks
taking app/phases/upgrade

**Comment by yagonobre** [comment]
I can take `alpha phase certs renew`

**Comment by yuexiao-wang** [comment]
taking  printing the join command

**Comment by yagonobre** [comment]
`alpha phase certs renew` was done in https://github.com/kubernetes/kubernetes/pull/70333, I can take `bootstrap-token` and `addons`.

**Comment by bart0sh** [comment]
I can take this: "app/phases/upgrade needs to be moved to generic kubeadm utils (not a phase)"

**Comment by bart0sh** [comment]
@yagonobre thanks for pointing it out. won't take it then. I thought it's not assigned:
```
 app/phases/upgrade needs to be moved to generic kubeadm utils (not a phase)

assigned: TODO
```

**Comment by neolit123** [comment]
sorry, just updated it.

**Comment by yagonobre** [comment]
What is the expected subphases on `bootstrap-token`? I'm taking `upload-config` in the meantime.

**Comment by neolit123** [comment]
@yagonobre 
> What is the expected subphases on bootstrap-token? I'm taking upload-config in the meantime.

as commented there, the listed sub-phases should be just collapsed in a single phase.
> should contain all of these, but collapsed and not exposed as sub-phases.

**Comment by yagonobre** [comment]
ok, taking `bootstrap-token` again

**Comment by neolit123** [comment]
> just a FYI, since this is the last phase in the order, we need to keep the PR open until we merge the previous phases, since we don't want to break e2e tests.

**Comment by fabriziopandini** [comment]
@neolit123 annotateCRI IMO doesn't deserve a first level phase because it ideally should go away as soon as possible.. What about having annotateCRI as part of the upload kubelet config subphases? (Run Upload kubelet config writes the config map and annotates CRI)
@yagonobre wdyt?

**Comment by neolit123** [comment]
added missing phases:
- wait-for-control-plane (i'm taking this one)
- annotate-cri-socket (anyone can take)

**Comment by neolit123** [comment]
@fabriziopandini 
SGTM, i will update the list.

**Comment by neolit123** [comment]
@RA489 hi, do you have a PR in the works for mark-control-plane?
we might be able to merge it this week if so.

**Comment by RA489** [comment]
@neolit123 WIP

**Comment by neolit123** [comment]
the work here is done!

the only remaining items are these, but we can track then individually:
https://github.com/kubernetes/kubernetes/pull/70346
https://github.com/kubernetes/kubernetes/pull/69979

we did a pretty nice organization here and managed to tackle the list of tasks pretty well!!
thank you @fabriziopandini @yagonobre  @yuexiao-wang @ereslibre @RA489

i will also send a shoutout to everyone for the community meeting on Thursday.
