### ISSUE TITLE
Tracking issue for Certificates copy for join --control-plane

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1373]
This is the tracking issue for the implementation of [Certificates copy for join --control-plane](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/20190122-Certificates-copy-for-kubeadm-join--control-plane.md), original issue [here](https://github.com/kubernetes/kubeadm/issues/1200). Help is welcome! If you want to pick up some  help wanted activity just write it in a comment; "on hold" means the activity should wait for some predecessor before being actively worked

**Certificates copy workflow**
- [x] https://github.com/kubernetes/kubeadm/issues/1374 Upload encrypted certs on init (@yagonobre https://github.com/kubernetes/kubernetes/pull/73907)
- [x] https://github.com/kubernetes/kubeadm/issues/1407 Use encrypted certs on join (@ereslibre https://github.com/kubernetes/kubernetes/pull/74168)
- [x] https://github.com/kubernetes/kubeadm/issues/1408 Alllow user to provide the certificate key on upload-certs (@yagonobre https://github.com/kubernetes/kubernetes/pull/74671)
- [ ] Periodic test in test-grid
     - [x] Make kind support multi control-plane without upload certs (@fabriziopandini https://github.com/kubernetes-sigs/kind/pull/233 https://github.com/kubernetes-sigs/kind/pull/164 https://github.com/kubernetes-sigs/kind/pull/147 https://github.com/kubernetes-sigs/kind/pull/143 https://github.com/kubernetes-sigs/kind/pull/137)
     - [x] kinder test utils (@neolit123/@fabriziopandini)
     - [x] Write a minimal e2e deployer for kinder in the kubeadm repo (@neolit123/@fabriziopandini)
     - [ ] Periodic job for multi control-plane without upload certs (@neolit123)
     - [x] Make kinder support upload certs (@neolit123/@fabriziopandini)
     - [ ] Periodic job for multi control-plane with upload certs (on hold/@neolit123)

**Other HA Improvements**
- [x] Improve init completion message for HA (@fabriziopandini https://github.com/kubernetes/kubernetes/pull/75420)
- [ ] Join control-plane improvements
   - [x] Pre pull images (@MalloZup https://github.com/kubernetes/kubernetes/pull/72870 )
   - [x] SANS validation (@ereslibre https://github.com/kubernetes/kubernetes/pull/73093)
   - [x] Wait for etcd joining the new member (@ereslibre  https://github.com/kubernetes/kubernetes/pull/72984)
   - [ ] Rename `--experimental-control-plane` into `--control-plane`  (on hold/moved to v1.15/@yuexiao-wang)
- [ ] Upgrade improvements
   - [ ] https://github.com/kubernetes/kubeadm/issues/1071 merge `kubeadm upgrade node experimental-control-plane` into `kubeadm upgrade node` (on hold/moved to v1.15 @yuexiao-wang)
- [x] Reset improvements
   - [x] https://github.com/kubernetes/kubeadm/issues/1312 Remove control-plane nodes from ClusterStatus (@neolit123 https://github.com/kubernetes/kubernetes/pull/75082)
   - [x] https://github.com/kubernetes/kubeadm/issues/1211 Remove etcd members from the etcd cluster (@pytimer https://github.com/kubernetes/kubernetes/pull/74112)

**Docs**
- [x] https://kubernetes.io/docs/setup/independent/high-availability/ v1.14 edition (@neolit123 https://github.com/kubernetes/website/pull/13191)

**Nice to have**
- [x] E2E test cases for `ClusterStatus` management in the `kubeadm-config` config-map (@fabriziopandini 
 https://github.com/kubernetes/kubernetes/pull/75641)
- [x] E2E test cases for `kubeadm-certs` secret (@fabriziopandini https://github.com/kubernetes/kubernetes/pull/75641)
- [ ] Periodic jobs for HA upgrades, For Add/Remove control-plane nodes etc. (on hold/**help wanted**)

**Comment by neolit123** [comment]
added myself to a couple of items.

**Comment by yagonobre** [comment]
I can take
```
 #1374 Upload encrypted certs on init (help wanted)
  Use encrypted certs on join (on hold/help wanted)
```

**Comment by ereslibre** [comment]
I can take `Use encrypted certs on join`

**Comment by yagonobre** [comment]
@ereslibre feel free to take this :)

**Comment by MalloZup** [comment]
i can take the ` E2E test cases for kubeadm-certs secret (on hold/help wanted)` for learning the E2E for kubeadm :rocket: .

If time allows i will might take also other interesting issues. ( should i create a sub-issue for that?). Tia

**Comment by yuexiao-wang** [comment]
I will work on ` #1071 merge kubeadm upgrade node experimental-control-plane into kubeadm upgrade node (help wanted)`

**Comment by fabriziopandini** [comment]
@yuexiao-wang please sync with @MalloZup because he was interested in `#1071 merge kubeadm upgrade node experimental-control-plane into kubeadm upgrade node (help wanted)` too

**Comment by pytimer** [comment]
@fabriziopandini I can take the #1211 if the remove etcd members can be added to the reset process.

**Comment by fabriziopandini** [comment]
@pytimer awesome, thanks!

**Comment by yagonobre** [comment]
https://github.com/kubernetes/kubeadm/issues/1408

**Comment by neolit123** [comment]
moving to 1.15 to not confuse the release team.

**Comment by fabriziopandini** [comment]
moving the remaing items to https://github.com/kubernetes/kubeadm/issues/1567
Thanks to all for helping in this effor
