### ISSUE TITLE
Update the 1.15 documentation

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1577]
tracking issue for 1.15 docs updates.

PRs:
- [x] setup: https://github.com/kubernetes/website/pull/14594
- [x]  tasks: https://github.com/kubernetes/website/pull/14595
- [x]  reference: https://github.com/kubernetes/website/pull/14596
- [x] v1beta2: https://github.com/kubernetes/website/pull/14607 (@rosti)
- [x] cert management: https://github.com/kubernetes/website/pull/14716 (@fabriziopandini @jimangel)

deadline for placeholders is the 31st
deadline for final docs is the 4th
https://github.com/kubernetes/sig-release/tree/master/releases/release-1.15#timeline

**Comment by yagonobre** [comment]
@neolit123 this prs include the changes on reset phase?

**Comment by neolit123** [comment]
yes

**Comment by RA489** [comment]
@neolit123 please include me in for some of the PRs

**Comment by SataQiu** [comment]
I am happy to be involved too. :laughing:

**Comment by neolit123** [comment]
it's OK, this cycle were are pressed for time after kubecon, so we i will try managing all (most) of the doc PRs.
thanks.

**Comment by RA489** [comment]
@neolit123 np, let me me if i can help with some other PRs

**Comment by neolit123** [comment]
all documentation PRs have merged.
will keep this open until release.

**Comment by neolit123** [comment]
we are done here.

**Comment by fabriziopandini** [comment]
@neolit123 thanks for coordinating this effort
