### ISSUE TITLE
Dual-Stack support for Kubeadm

### ISSUE THREAD

**Issue by Arvinderpal** [kubernetes/kubeadm#1612]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

In order to support the forthcoming dual-stack work, certain changes must be made to kubeadm so that it can create dual-stack clusters. The dual-stack KEP (https://github.com/kubernetes/enhancements/pull/808) has a section on changes required in kubeadm. 

Phase-1 Tasks:

- [x] kubeadm feature-gate https://github.com/kubernetes/kubernetes/pull/80145
- [x] Propagate kubeadm feature-gate to all k8s components https://github.com/kubernetes/kubernetes/pull/80531
- [x] `--cluster-cidr` support for comma delimited list of IPs https://github.com/kubernetes/kubernetes/pull/79033
- [x] e2e tests for `--cluster-cidr`/`PodSubnet` changes https://github.com/kubernetes/kubernetes/pull/80947

Phase-2 Tasks:

- [x] `service-cluster-ip-range` support for dual-stack. https://github.com/kubernetes/kubernetes/pull/82473
- [x] e2e tests for `service-cluster-ip-range` (these are in kind upstream)
- [x] Add documentation on enabling dual-stack via kubadm
https://github.com/kubernetes/website/pull/26675

Additional Tasks:
- [x] Option `node-cidr-mask-size` to kube-controller manager needs to support a list of CIDRs. This currently defaults to /24 (for both ipv4 and ipv6). Func `calcNodeCidrSize` must be updated to handle dual-stack. https://github.com/kubernetes/kubernetes/pull/85609
- [x] don't hardcode the ipv4 mask size to 24?
https://github.com/kubernetes/kubeadm/issues/2327
https://github.com/kubernetes/kubernetes/issues/90922
fixed in:
https://github.com/kubernetes/kubernetes/commit/8b52995d328a50169924eb27d8d03cb47a9ceac6#diff-d870edeb820f49abf2f52cd357a8a5396c7cd1a36e024d339146e512186c7297

GA (1.23):
- [x] Add `apiserver-advertise-address` support for dual-stack
looks like this is no longer a goal
- [x] k/k PR that graduates the FG to GA:
https://github.com/kubernetes/kubernetes/pull/104691
- [x] move kubeadm's FG to GA + cleanup:
https://github.com/kubernetes/kubernetes/pull/104770

post-GA (1.24)
- [ ] remove the kubeadm feature gate and extra code related to it
- [ ] cleanup docs pages such as:
https://github.com/kubernetes/website/blob/082116588c191f52de2003deb71ce7a304cc357d/content/en/docs/setup/production-environment/tools/kubeadm/dual-stack-support.md

**Comment by neolit123** [comment]
thanks for logging the ticket @Arvinderpal 
@aojea has been interested in implementing IPV6 support in [kind](https://github.com/kubernetes-sigs/kind), which uses kubeadm under the hood and adding testing signal for that.

@aojea please take a look and communicate with @Arvinderpal who wishes to add dual stack support in kubeadm.

/assign @aojea @Arvinderpal

**Comment by neolit123** [comment]
the IPV6 PRs merged in kind.
https://github.com/kubernetes-sigs/kind/pull/636
also for test signal:
https://github.com/kubernetes/test-infra/pull/13123

**Comment by BenTheElder** [comment]
been keeping an eye on the dual stack work for exactly this @neolit123 👀

**Comment by Arvinderpal** [comment]
@neolit123 I would like to add a doc for setting up dual-stack with kubeadm. I have a draft ready. Where would be a good place to add this?

**Comment by neolit123** [comment]
hi @Arvinderpal we decided to do that for the beta release. is dual-stack going beta in 1.17?
if not possibly we should delay these docs until the beta.

also i'm on PTO this week and please direct any review requests to the rest of the group. :)

**Comment by sftim** [comment]
I'm concerned about a `/24` default netblock allocation for IPv6. That's really large; it'd be more realistic to default to a `/64` and let cluster operators override that if they know better.

**Comment by neolit123** [comment]
@sftim 

> I'm concerned about a /24 default netblock allocation for IPv6. That's really large; it'd be more realistic to default to a /64 and let cluster operators override that if they know better.

@Arvinderpal should correct me, but i think such decisions are on the plate of SIG Network.

**Comment by Arvinderpal** [comment]
I totally agree that /24 is not appropriate for IPv6. It's more a carryover from IPv4. 

> @Arvinderpal should correct me, but i think such decisions are on the plate of SIG Network.
Yes, sig-network is the right place.

**Comment by aojea** [comment]
IIRC /24 is a legacy thing and we can't change it until this merge https://github.com/kubernetes/kubernetes/pull/79993

**Comment by neolit123** [comment]
@Arvinderpal @aojea hi, are we going to see Beta graduation for this feature in core k8s for 1.19?

**Comment by aojea** [comment]
> @Arvinderpal @aojea hi, are we going to see Beta graduation for this feature in core k8s for 1.19?

KEP is going to be updated soon , seems this is the intention https://github.com/kubernetes/kubernetes/pull/86895#issuecomment-606924359

**Comment by neolit123** [comment]
thanks, @Arvinderpal would you be able to contribute any related changes to kubeadm for 1.19?

**Comment by Arvinderpal** [comment]
@neolit123 I have not been following the recent developments in dual-stack; however, if there are specific kubeadm changes needed, I can certainly make the time to help.

**Comment by neolit123** [comment]
@Arvinderpal thanks. hopefully you will have the time if the feature moves forward as users will have the expectation that kubeadm supports the latest incarnation. otherwise we have to explain the discrepancy to them.

**Comment by fabriziopandini** [comment]
@aojea are you planning to get dual-stack support in kind?

**Comment by aojea** [comment]
> @aojea are you planning to get dual-stack support in kind?

absolutely, I have also a PR working https://github.com/kubernetes-sigs/kind/pull/692, but we've decided to hold until the dual-stack feature is more stable. There are still lots of things to solve in the dual-stack area ...

**Comment by neolit123** [comment]
help-wanted with resolving this item:
> don't hardcode the ipv4 mask size to 24?

@sidharthsurana recently logged the same issue here:
https://github.com/kubernetes/kubeadm/issues/2327

**Comment by aojea** [comment]
I'll take it @neolit123

**Comment by aojea** [comment]
so, 

 > e2e tests for service-cluster-ip-range

These are being tested implicitly with the presubmit and periodic jobs https://testgrid.k8s.io/sig-network-kind#sig-network-kind,%20dual,%20master

> Add documentation on enabling dual-stack via kubadm

This seems the only part missing

>  Add apiserver-advertise-address support for dual-stack

Sig network started to discuss it recently ... that is not going to be resolved soon and is not clear how to move forward

**Comment by aojea** [comment]
/assign 
so I don´t forget,
 I will be the backup if nobody picks it

**Comment by pacoxu** [comment]
> /assign 
> 
> so I don´t forget,
> 
>  I will be the backup if nobody picks it

I can pick it. 😄 @aojea 

I have done a similar thing before on dual-stack 1.18 which is a little differeny.

**Comment by aojea** [comment]
/unassign
/assign @pacoxu 
Appreciate it,
Thanks

**Comment by pacoxu** [comment]
Action Items in 1.21：

- [ ] feature gate alpha to beta [cmd/kubeadm/app/features/features.go](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/features/features.go#L39), it need wait for [pkg/features/kube_features.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go#L747) change.
- [ ] Documentation: Add documentation on enabling dual-stack via kubadm.
- [No Work]Add apiserver-advertise-address support for dual-stack （keep it as before ?)

Is there anything that I miss?

**Comment by neolit123** [comment]
that's it. my understanding is that `apiserver-advertise-address` is not going to happen in 1.21.

**Comment by pacoxu** [comment]
@neolit123  @aojea 
Should we support multi node IPs in `kubeadm init` and `join`? 
- auto-detect or with a flag `--node-ips`
- if dual-stack is true, detect both; if single-stack, prefer ipv4 or detect from pod-cidr first.

**Comment by aojea** [comment]
I think so, or your hostnetwork pods will be single-stack, that can be a problem ...

**Comment by neolit123** [comment]
well, given kubeadm already supports passing kubelet config / flags we should just document how users can do that.
i don't think we should expose this is a wrapper in the kubeadm config or kubeadm flags.

arguably the kubeadm flag --node-name should not exist for similar reasons, but it's already there.

**Comment by aojea** [comment]
documentation is fine, I didn't want to mean to create a new option

**Comment by pacoxu** [comment]
@neolit123  node-ips auto detect should be a kubelet feature in my mind.
Currently, we can add it to the docs for reminding users.

**Comment by aojea** [comment]
> @neolit123 node-ips auto detect should be a kubelet feature in my mind.
> Currently, we can add it to the docs for reminding users.

the user has to specify the IP addresses of each family, separated by comma, there is no autodetect for dual-stack

**Comment by pacoxu** [comment]
Per https://github.com/kubernetes/enhancements/issues/563#issuecomment-830411731, it will wait to 1.23

**Comment by neolit123** [comment]
looks like the FG is moving to GA in 1.23:
https://github.com/kubernetes/kubernetes/pull/104691

this mean we can remove the kubeadm FG + handling in 1.24 or later.

**Comment by pacoxu** [comment]
In 1.23 kubeadm, we may change the FG to hidden like below after kubernetes/kubernetes#104691 is merged.
```
		IPv6DualStack:   {FeatureSpec: featuregate.FeatureSpec{Default: true, PreRelease: featuregate.GA}, HiddenInHelpText: true},
```

**Comment by khenidak** [comment]
Folks -- Do you want me to address gate removal in PR kubernetes/kubernetes#104691 - or do you want to take care of it separatly?

@neolit123 @pacoxu @aojea

**Comment by neolit123** [comment]
for 1.23 in kubeadm we should just change this line:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/features/features.go#L42

to be exactly this:
```
IPv6DualStack:   {FeatureSpec: featuregate.FeatureSpec{Default: true, LockToDefault: true, PreRelease: featuregate.GA}, HiddenInHelpText: true},
```

^ `LockToDefault` is true, i'm assuming this also has to happen for the core feature gate - i.e. when the FG goes GA we are going to lock it to `true`.
it also includes `HiddenInHelpText: true` as @pacoxu pointed out above (this is a kubeadm specific FG property).
you can do that in the https://github.com/kubernetes/kubernetes/pull/104691 PR.

IMO, the cleanup of logic around the `IPv6DualStack` feature gate checks in kubeadm can be done when the kubeadm FG is removed. we can do that in 1.24 (one release after the FG goes GA).
not sure what the core maintainers prefer for the core logic, but making the kubeadm changes in 1.24 and separate PR seems like less noise.

seems like core generally prefers to remove the FG logic when a FG goes GA and not when the FG is removed - e.g.:
https://github.com/kubernetes/kubernetes/pull/97543
(@pacoxu you did this change for LegacyNodeRoleBehavior)

**Comment by pacoxu** [comment]
> seems like core generally prefers to remove the FG logic when a FG goes GA and not when the FG is removed 

Yes. Either is ok(in 1.23 or 1.24).

@khenidak  As Lubomir points out, you can just update the [cmd/kubeadm/app/features/features.go#L42](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/features/features.go#L42). 

The removal of the FG logic in kubeadm can be done in your PR or a separate PR which is just a cleanup. Either is OK.

**Comment by khenidak** [comment]
Ok - I will update the feature file. But will not touch the rest. Thank you.

**Comment by neolit123** [comment]
we cleaned up the feature gate from kubeadm (1.24):
https://github.com/kubernetes/kubernetes/pull/106648

thanks everyone for helping with this.
