### ISSUE TITLE
v1beta3 config

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1796]
k/e issue:
https://github.com/kubernetes/enhancements/issues/970

KEP update:
https://github.com/kubernetes/enhancements/pull/2627

KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/kubeadm/970-kubeadm-config

full list of pending changes:
https://github.com/kubernetes/kubeadm/labels/kind%2Fapi-change

PRs:
- [x] add v1beta3 / remove v1beta1:
https://github.com/kubernetes/kubernetes/pull/101129
- [x] set v1beta3 as preferred version in k/website docs pages
https://github.com/kubernetes/website/pull/28360

Prioritization for 1.22 as discussed during the kubeadm office hours of 31st of March 2021. this is mostly user feedback based.
(P0 == highest priority)

- [x] P0: Skip phases / addons
https://github.com/kubernetes/kubeadm/issues/2261
https://github.com/kubernetes/kubernetes/pull/101923
- [x] P0: remove DNS.Type
https://github.com/kubernetes/kubeadm/issues/1889
https://github.com/kubernetes/kubernetes/pull/101547
- [x] P0: remove  useHyperkubeImage
https://github.com/kubernetes/kubeadm/issues/2398
https://github.com/kubernetes/kubernetes/pull/101537
- [x] P1: Add object meta and +optional tags (CRD friendly)
https://github.com/kubernetes/kubeadm/issues/1727
https://github.com/kubernetes/kubernetes/pull/101925
- [x] P1: remove ClusterStatus:
https://github.com/kubernetes/kubeadm/issues/2290
https://github.com/kubernetes/kubernetes/pull/101915
- [x] P2: breakout BootstrapToken* from v1beta3 into a new group bootstraptoken/v1
https://github.com/kubernetes/kubeadm/issues/2427
https://github.com/kubernetes/kubernetes/pull/102964
- [x] ~P3: customize /var/run/kubelet~ (dropped from v1beta3)
https://github.com/kubernetes/kubeadm/issues/2104
- [x] P3: tag with datapolicy:
https://github.com/kubernetes/kubeadm/issues/2339
https://github.com/kubernetes/kubernetes/pull/102174
- [x] P3: add patches to config?
https://github.com/kubernetes/kubeadm/issues/2046
https://github.com/kubernetes/kubernetes/pull/103063
- [x] ~P3: pause image configurable:~ (dropped as an idea)
~https://github.com/kubernetes/kubeadm/issues/2020~
- [x] ~P3: extra args duplicates~ (dropped from v1beta3):
https://github.com/kubernetes/kubeadm/issues/1601
- [x] P3: imagePullPolicy
https://github.com/kubernetes/kubeadm/issues/524
https://github.com/kubernetes/kubernetes/pull/102901
- [x] ~P3: ETCSA as optional keys~ (dropped from v1beta3):
~https://github.com/kubernetes/kubeadm/issues/1535~
- [x] ~P3: move timeouts to sub-structures~ (dropped from v1beta3):
https://github.com/kubernetes/kubeadm/issues/2463

**Comment by neolit123** [comment]
saw the VOD of the kubeadm planning and created this ticket.

**Comment by neolit123** [comment]
ncdc proposed that we add "image pull policy" support to the kubeadm api.
see the issue that was caused here and the PR revert:
https://github.com/kubernetes/kubernetes/pull/85965

**Comment by Random-Liu** [comment]
Can we make pause image repository and tag configurable?

People may build and use a different pause image. :)

Here is an example PR: https://github.com/kubernetes/kubernetes/pull/87827

**Comment by rosti** [comment]
> Can we make pause image repository and tag configurable?
> 
> People may build and use a different pause image. :)
> 
> Here is an example PR: [kubernetes/kubernetes#87827](https://github.com/kubernetes/kubernetes/pull/87827)

@Random-Liu thanks for the suggestion!
I moved the discussion to #2020 . Let's continue there on that topic.

**Comment by pacoxu** [comment]
👍
kubernetes/website#28360 seems to be the last step.

**Comment by neolit123** [comment]
the API is out and this can be closed.
