### ISSUE TITLE
1.17: Housekeeping tasks

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1807]
This is a tracking issue for tasks that we are required to carry out during each cycle.

_At the beginning of the cycle_
- [x] [@neolit123] Cleanup E2E jobs for 1.13 (current -3) rif https://github.com/kubernetes/kubeadm/pull/1804 and kubernetes/test-infra#14483
- [x] [@fabriziopandini] Bump minimum supported versions rif https://github.com/kubernetes/kubernetes/pull/83312 (v1.16 https://github.com/kubernetes/kubernetes/pull/80833)
- [x] [@fabriziopandini] Add etcd version for v1.18 rif https://github.com/kubernetes/kubernetes/pull/83314 (v1.16 https://github.com/kubernetes/kubernetes/pull/81386)

_When the 1.17 branch is created_
- [x] [@hypnoglow] Create E2E jobs for 1.17 rif https://github.com/kubernetes/kubeadm/pull/1879 and https://github.com/kubernetes/test-infra/pull/15077 (v1.16 https://github.com/kubernetes/kubeadm/pull/1744 and https://github.com/kubernetes/test-infra/pull/14037)
- [x] [@neolit123] Update the kubeadm upgrade docs for this release (v1.17 https://github.com/kubernetes/website/pull/17587)

_Before the 1.18 cycle start_
- [ ] Duplicate this issue for tracking 1.18 housekeeping tasks
- [ ] Close this issue

**Comment by fabriziopandini** [comment]
Taking "Bump minimum supported versions" and "Add etcd version for v1.18"

**Comment by neolit123** [comment]
> This is a tracking issue for tasks that we are required to carry out during each cycle.
> 
> _At the beginning of the cycle_
> 
> * [x]  [@neolit123] Cleanup E2E jobs for 1.13 (current -3) rif #1804 and [kubernetes/test-infra#14483](https://github.com/kubernetes/test-infra/pull/14483)
> * [x]  [@fabriziopandini] Bump minimum supported versions rif [kubernetes/kubernetes#83312](https://github.com/kubernetes/kubernetes/pull/83312) (v1.16 [kubernetes/kubernetes#80833](https://github.com/kubernetes/kubernetes/pull/80833))
> * [x]  [@fabriziopandini] Add etcd version for v1.18 rif [kubernetes/kubernetes#83314](https://github.com/kubernetes/kubernetes/pull/83314) (v1.16 [kubernetes/kubernetes#81386](https://github.com/kubernetes/kubernetes/pull/81386))
> 
> _When the 1.17 branch is created_
> 
> * [x]  [@hypnoglow] Create E2E jobs for 1.17 rif #1879 and [kubernetes/test-infra#15077](https://github.com/kubernetes/test-infra/pull/15077) (v1.16 #1744 and [kubernetes/test-infra#14037](https://github.com/kubernetes/test-infra/pull/14037))
> * [x]  [@neolit123] Update the kubeadm upgrade docs for this release (v1.17 [kubernetes/website#17587](https://github.com/kubernetes/website/pull/17587))
> 
> _Before the 1.18 cycle start_
> 
> * [ ]  Duplicate this issue for tracking 1.18 housekeeping tasks
> * [ ]  Close this issue
