### ISSUE TITLE
1.18: Housekeeping tasks

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1963]
This is a tracking issue for tasks that we are required to carry out during each cycle.

_When .1 patch version is created_
- [x] [@neolit123] Cleanup E2E jobs for 1.14 (current -3) (requires two PRs)
https://github.com/kubernetes/kubeadm/pull/1965
https://github.com/kubernetes/test-infra/pull/15576
- [x] [@neolit123] Bump minimum supported versions
https://github.com/kubernetes/kubernetes/pull/88347/commits/22319019abc1590d022d76685d0b
(rif https://github.com/kubernetes/kubernetes/pull/83312 v1.16 https://github.com/kubernetes/kubernetes/pull/80833)
- [x] [@neolit123] Add etcd version for v1.18
https://github.com/kubernetes/kubernetes/pull/88347/commits/22319019abc1590d022d76685d0bb663d36c3222
(rif https://github.com/kubernetes/kubernetes/pull/83314 v1.16 https://github.com/kubernetes/kubernetes/pull/81386)

_When the 1.18 branch is created_
- [x] [@neolit123] Create E2E jobs for 1.18
https://github.com/kubernetes/kubeadm/pull/2044
(1.18 example PR https://github.com/kubernetes/kubeadm/pull/2044, test-infra PR https://github.com/kubernetes/test-infra/pull/16527)
- [x] [@neolit123 ] Update the kubeadm upgrade docs for this release
https://github.com/kubernetes/website/pull/19551
(v1.17  example PR https://github.com/kubernetes/website/pull/17587)

_Before the 1.19 cycle start_
- [ ] Duplicate this issue for tracking 1.19 housekeeping tasks
- [ ] Close this issue

same issue for 1.17:
https://github.com/kubernetes/kubeadm/issues/1963
