### ISSUE TITLE
1.19: Housekeeping tasks

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2076]
This is a tracking issue for tasks that we are required to carry out during each cycle.
**It tracks the upcoming release of Kubernetes 1.19 (1.x)**

same issue for 1.18 (see example PRs):
https://github.com/kubernetes/kubeadm/issues/1963

_When the first 1.x tag is created_
- [x] [@fabriziopandini] drop kinder support for 1.x-4:
https://github.com/kubernetes/kubeadm/pull/2088

_When 1.x-1.1 patch version is created_
- [x] [@neolit123 ] Cleanup E2E jobs for 1.x-3 (requires two PRs)
https://github.com/kubernetes/kubeadm/pull/2105
https://github.com/kubernetes/test-infra/pull/17209
- [x] [@neolit123] Bump minimum supported versions
https://github.com/kubernetes/kubernetes/pull/90144
- [x] [@neolit123] Add etcd version for 1.x and placeholder for 1.x+1
https://github.com/kubernetes/kubernetes/pull/89895, https://github.com/kubernetes/kubernetes/pull/90144

_When the release-1.x branch is created_
- [x] [@RA489 ] Create E2E jobs for 1.x
https://github.com/kubernetes/kubeadm/pull/2113
- [x] [@neolit123] Update the kubeadm upgrade docs for this release
https://github.com/kubernetes/website/pull/21860
https://github.com/kubernetes/website/pull/21663

Related PRs:
- [x] [@neolit123] Cleanup 1.15 jobs and kinder logic due to a missing latest-1.15 version label:
https://github.com/kubernetes/test-infra/pull/18700
https://github.com/kubernetes/kubeadm/pull/2248
(drops kinder support for 1.x-4)

_Before the 1.x+1 cycle start_
- [x] Duplicate this issue for tracking 1.x+1 housekeeping tasks
- [x] Close this issue

**Comment by fabriziopandini** [comment]
@neolit123 this list should be amended by adding a new task for removing support for v -4 from kinder

**Comment by neolit123** [comment]
@fabriziopandini updated.

**Comment by neolit123** [comment]
this is done.
new issue here for .20:
https://github.com/kubernetes/kubeadm/issues/2277
/close
