### ISSUE TITLE
1.20: Housekeeping tasks

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2277]
This is a tracking issue for tasks that we are required to carry out during each cycle.
**It tracks the upcoming release of Kubernetes 1.20 (1.x)**

same issue for 1.19 (see example PRs):
https://github.com/kubernetes/kubeadm/issues/2076

_When the first 1.x tag is created_
- [x] [@neolit123] drop kinder support for 1.x-4 and older:
https://github.com/kubernetes/kubeadm/pull/2248

_When 1.x-1.1 patch version is created_
- [x] [@Akhilesh2412] Cleanup E2E jobs for 1.x-4 (requires two PRs)
https://github.com/kubernetes/kubeadm/pull/2282
https://github.com/kubernetes/test-infra/pull/19164
- [x] [@Akhilesh2412] Bump minimum supported versions and add etcd version for 1.x and placeholder for 1.x+1
https://github.com/kubernetes/kubernetes/pull/94664

_When the release-1.x branch is created_
- [x] [@RA489 ] Create E2E jobs for 1.x
https://github.com/kubernetes/kubeadm/pull/2337
https://github.com/kubernetes/test-infra/pull/19852
- [x] [@neolit123] **NO LONGER NEEDED FOR 1.21 onwards.** Update the kubeadm upgrade docs for this release
https://github.com/kubernetes/website/pull/24908

_Before the 1.x+1 cycle start_
- [x] Duplicate this issue for tracking 1.x+1 housekeeping tasks
- [x] Close this issue

**Comment by Akhilesh2412** [comment]
May I work on this?

**Comment by neolit123** [comment]
@Akhilesh2412 the "Bump minimum supported versions" task is a fairly easy too, so you can take a look at that too if you want.

**Comment by Akhilesh2412** [comment]
@neolit123 Sure. Taking that up.

**Comment by Akhilesh2412** [comment]
@neolit123 I was unsure about the etcd version. If possibel please do tell me those too will finish them in this PR only.

**Comment by neolit123** [comment]
thanks for the PRs @Akhilesh2412 
we are done with the tasks for now, but they should continue later once the release-1.20 branch is created:

> When the release-1.x branch is created
> ...

**Comment by RA489** [comment]
Taking  Create E2E jobs for 1.x

**Comment by neolit123** [comment]
this is done.
1.21 ticket is here: https://github.com/kubernetes/kubeadm/issues/2362
