### ISSUE TITLE
1.21: housekeeping tasks

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2362]
This is a tracking issue for tasks that we are required to carry out during each cycle.
**It tracks the upcoming release of Kubernetes 1.21 (1.x)**

same issue for 1.20 (see example PRs):
https://github.com/kubernetes/kubeadm/issues/2277

_When 1.x-1.1 patch version is created_
- [x] Drop kinder support for 1.x-4 and older
(not needed since 1.16 support was already removed previously)
- [x] Cleanup E2E jobs for 1.x-4 (requires two PRs)
https://github.com/kubernetes/kubeadm/pull/2378
https://github.com/kubernetes/test-infra/pull/20531
- [x] Bump minimum supported versions and add etcd version for 1.x and placeholder for 1.x+1
https://github.com/kubernetes/kubernetes/pull/98008

_When the release-1.x branch is created_
- [x] [@RA489] Create E2E jobs for 1.x
https://github.com/kubernetes/kubeadm/pull/2412
https://github.com/kubernetes/test-infra/pull/21643

_Before the 1.x+1 cycle start_
- [x] Duplicate this issue for tracking 1.x+1 housekeeping tasks
- [x] Close this issue

**Comment by RA489** [comment]
taking Cleanup E2E jobs and Bump minimum supported versions

**Comment by pacoxu** [comment]
taking ` [TODO] Drop kinder support for 1.x-4 and older`
/assign

**Comment by RA489** [comment]
taking Create E2E jobs for 1.x once 1.x branch is created.

**Comment by pacoxu** [comment]
Forget to handle this one in 1.21 😅

**Comment by RA489** [comment]
> Forget to handle this one in 1.21

@pacoxu not needed in this cycle since 1.16 support was already removed previously

**Comment by neolit123** [comment]
created a tool for automating the e2e test setup.
this can be reviewed and potentially merge for 1.22:
https://github.com/kubernetes/kubeadm/pull/2434

**Comment by neolit123** [comment]
1.22 issue is here:
https://github.com/kubernetes/kubeadm/issues/2440
