### ISSUE TITLE
1.22: housekeeping tasks

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2440]
This is a tracking issue for tasks that we are required to carry out during each cycle.
**It tracks the upcoming release of Kubernetes 1.22 (1.x)**

Note: make sure you reference this issue in PRs.

same issue for 1.21 (see example PRs):
https://github.com/kubernetes/kubeadm/issues/2362

_When the last 1.x-4 patch version is released_
- [x] [@CaoDonghui123] Drop kinder support for 1.x-4 and older
https://github.com/kubernetes/kubeadm/pull/2447
- [x] [@CaoDonghui123] Cleanup E2E jobs for 1.x-4 (requires two PRs)
set `KUBERNETES_VERSION` to 1.x-1 and `KUBERNETES_SKEW` to `2` in /kinder/hack/update-workflows.sh
make sure `PATH_TEST_INFRA` points to the right path.
run the script and send two PRs for k/kubeadm and k/test-infra.
https://github.com/kubernetes/kubeadm/pull/2456
https://github.com/kubernetes/test-infra/pull/21905
- [x] [@niulechuan] Bump minimum supported versions and add etcd version for 1.x and placeholder for 1.x+1
https://github.com/kubernetes/kubernetes/pull/101104

_When the release-1.x branch is created_
- [x] [@RA489] Create E2E jobs for 1.x
set `KUBERNETES_VERSION` to 1.x and `KUBERNETES_SKEW` to `3` in /kinder/hack/update-workflows.sh
make sure `PATH_TEST_INFRA` points to the right path.
run the script and send two PRs for k/kubeadm and k/test-infra.
https://github.com/kubernetes/kubeadm/pull/2533
https://github.com/kubernetes/test-infra/pull/23019

_Before the 1.x+1 cycle start_
- [x] Duplicate this issue for tracking 1.x+1 housekeeping tasks
- [x] Close this issue

**Comment by niulechuan** [comment]
/assign
I will take ` [TODO] Bump minimum supported versions and add etcd version for 1.x and placeholder for 1.x+1`

**Comment by CaoDonghui123** [comment]
/assign
I will work for [TODO] Cleanup E2E jobs for 1.x-4

**Comment by neolit123** [comment]
@CaoDonghui123

please hold on this work until https://github.com/kubernetes/kubeadm/pull/2434 is merged.
it adds a tool to help with the test jobs updates.

**Comment by CaoDonghui123** [comment]
All right. I notice that update-workflow.sh does not exist.
I will check it.

**Comment by RA489** [comment]
taking Create E2E jobs for 1.x

**Comment by neolit123** [comment]
the release-1.22 branch and testgrid dashboards for 1.22 were created:
we can proceed with:
> taking Create E2E jobs for 1.x

**Comment by RA489** [comment]
> the release-1.22 branch and testgrid dashboards for 1.22 were created:
> https://github.com/kubernetes/kubernetes/tree/release-1.22
> https://k8s-testgrid.appspot.com/sig-release
> 
> we can proceed with:
> 
> > [TODO] Create E2E jobs for 1.x

PR is in flight.

**Comment by RA489** [comment]
@neolit123 Thank you for the great work!!! https://github.com/kubernetes/kubeadm/pull/2434

**Comment by neolit123** [comment]
this is done.

1.23 issue is here:
https://github.com/kubernetes/kubeadm/issues/2539
