### ISSUE TITLE
deprecate and remove the kubeadm v1beta2 API

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2459]
**NOTE: this is just a tracking issue for future work!**

possibly after kubeadm v1.23 (e.g. 1.24):

- [x] deprecate v1beta2
  - [x] make kubeadm warn about the deprecated API
https://github.com/kubernetes/kubernetes/pull/107013
  - [x] update k/website and other docs to indicate that the API is deprecated
not needed (?) as this page uses the doc.go from v1beta2 https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta2/ and we are adding a deprecated note in it.

-------

future version (possibly 1.24 + one year (1.27))

- [ ] remove v1beta2
  - [ ] remove from the internal type - ClusterConfiguration.UseHyperKubeImage and other v1beta2 features that are not present in v1beta3
  - [ ] update e2e tests
  - [ ] ?

**Comment by pacoxu** [comment]
This sound can be made in v1.27.

Not sure if this can be done in this release or later?

**Comment by neolit123** [comment]
yes, it's scheduled for .27

> future version (possibly 1.24 + one year (1.27))
