### ISSUE TITLE
1.23: housekeeping tasks

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2539]
This is a tracking issue for tasks that we are required to carry out during each cycle.
**It tracks the upcoming release of Kubernetes 1.23 (1.x)**

Note: make sure you reference this issue in PRs.

same issue for 1.22 (see example PRs):
https://github.com/kubernetes/kubeadm/issues/2440

_When 1.x-4 version goes out of support_
https://kubernetes.io/releases/#release-history

- [x] Drop kinder support for 1.x-4 and older (may not be needed every release)
- [x] Cleanup E2E jobs for 1.x-4 (requires two PRs)
set `KUBERNETES_VERSION` to 1.x-1 and `KUBERNETES_SKEW` to `2` in /kinder/hack/update-workflows.sh
make sure `PATH_TEST_INFRA` points to the right path.
run the script and send two PRs for k/kubeadm and k/test-infra.
https://github.com/kubernetes/kubeadm/pull/2558
https://github.com/kubernetes/test-infra/pull/23346
- [x] Vendor the latest system-validators in kubernetes/kubernetes (may not be needed every release)
https://github.com/kubernetes/kubernetes/issues/104246

_When the release-1.x branch and release-1.x test dashboards are created_
- [x] Create E2E jobs for 1.x
set `KUBERNETES_VERSION` to 1.x and `KUBERNETES_SKEW` to `3` in /kinder/hack/update-workflows.sh
make sure `PATH_TEST_INFRA` points to the right path.
run the script and send two PRs for k/kubeadm and k/test-infra.

_Before the 1.x+1 cycle start_
- [x] Duplicate this issue for tracking 1.x+1 housekeeping tasks
- [ ] Close this issue

**Comment by RA489** [comment]
taking Drop kinder support  & Cleanup E2E jobs for 1.x-4
/assign

**Comment by RA489** [comment]
test nfra PR : https://github.com/kubernetes/test-infra/pull/24442

**Comment by neolit123** [comment]
1.24 issue is here:
https://github.com/kubernetes/kubeadm/issues/2539
