### ISSUE TITLE
1.24: housekeeping tasks

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2621]
This is a tracking issue for tasks that we are required to carry out during each cycle.
**It tracks the upcoming release of Kubernetes 1.24 (1.x)**

Note: make sure you reference this issue in PRs.

same issue for 1.23 (see example PRs):
https://github.com/kubernetes/kubeadm/issues/2539

_When 1.x-4 version goes out of support_
https://kubernetes.io/releases/#release-history

- [x] Drop kinder support for 1.x-4 and older (may not be needed every release)
- [x] Cleanup E2E jobs for 1.x-4 (requires two PRs)
set `KUBERNETES_VERSION` to 1.x-1 and `KUBERNETES_SKEW` to `2` in /kinder/hack/update-workflows.sh
make sure `PATH_TEST_INFRA` points to the right path.
run the script and send two PRs for k/kubeadm and k/test-infra.
https://github.com/kubernetes/test-infra/pull/25065
https://github.com/kubernetes/kubeadm/pull/2644
- [x] Vendor the latest system-validators in kubernetes/kubernetes (may not be needed every release)
https://github.com/kubernetes/kubernetes/pull/108988

_When the release-1.x branch and release-1.x test dashboards are created_
- [x] Create E2E jobs for 1.x
set `KUBERNETES_VERSION` to 1.x and `KUBERNETES_SKEW` to `3` in /kinder/hack/update-workflows.sh
make sure `PATH_TEST_INFRA` points to the right path.
run the script and send two PRs for k/kubeadm and k/test-infra.
https://github.com/kubernetes/kubeadm/pull/2675
https://github.com/kubernetes/test-infra/pull/25779

_Before the 1.x+1 cycle start_
- [x] Duplicate this issue for tracking 1.x+1 housekeeping tasks
- [ ] Close this issue

**Comment by pacoxu** [comment]
> * [ ]  Vendor the latest system-validators in kubernetes/kubernetes (may not be needed every release)

https://github.com/kubernetes/kubernetes/pull/108988 was merged. All 1.24 tasks are done.

**Comment by RA489** [comment]
> All 1.24 tasks are done.
@pacoxu https://github.com/kubernetes/kubeadm/pull/2675 still remaining to be merged once the release-1.22 branch and testgrid dashboards for 1.22 were created

**Comment by neolit123** [comment]
1.25 issue https://github.com/kubernetes/kubeadm/issues/2694
