### ISSUE TITLE
Kubeadm phase implementation checklist

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#267]
This checklist tracks action items for implementing phases in kubeadm, addressing @luxas [proposal](https://github.com/kubernetes/kubeadm/pull/156/files) and related comments.

Common implementation guidelines and principles for all phases are defined [here](https://docs.google.com/document/d/1VQMyFIVMfRGQPP3oCUpfjiWtOr3pLxp4g7cP-hXQFXc/edit?usp=sharing)

**Core activities**
- [x] kubeadm phase certs [PR #45617](https://github.com/kubernetes/kubernetes/pull/45617) 
  - [x] kubeadm phase certs all
  - [x] kubeadm phase certs ca
  - [x] kubeadm phase certs apiserver
  - [x] kubeadm phase certs apiserver-kubelet-client
  - [x] kubeadm phase certs sa
  - [x] kubeadm phase certs front-proxy-ca
  - [x] kubeadm phase certs front-proxy-client
- [x] kubeadm phase kubeconfig [PR #49419](https://github.com/kubernetes/kubernetes/pull/49419)
  - [x] kubeadm phase kubeconfig all
  - [x] kubeadm phase kubeconfig admin
  - [x] kubeadm phase kubeconfig kubelet
  - [x] kubeadm phase kubeconfig scheduler
  - [x] kubeadm phase kubeconfig controller-manager
  - [x] kubeadm phase kubeconfig user
- [x] kubeadm phase controlplane [PR #50302](https://github.com/kubernetes/kubernetes/pull/50302)
  - [x] kubeadm phase controlplane all
  - [x] kubeadm phase controlplane etcd
  - [x] kubeadm phase controlplane apiserver
  - [x] kubeadm phase controlplane scheduler
  - [x] kubeadm phase controlplane controller-manager
  - [ ] ~~kubeadm phase controlplane self-hosted (to be confirmed)~~
- [x] kubeadm phase bootstrap 
  - [x] kubeadm phase bootstrap mark-master
  - [x] kubeadm phase bootstrap token (essentially the same of kubeadm token create <token>)
  - [x] kubeadm phase bootstrap cluster-info
- [ ] kubeadm phase addons
Required addons for setting up a cluster are:   
  - [ ] kubeadm phase addons kube-proxy (includes service accounts/RBAC rules)
  - [ ] kubeadm phase addons kube-dns (includes service accounts/RBAC rules)

**Support activities**
- [x] Review package structure in order to share among different phases  `SetInitDynamicDefaults(cfg *MasterConfiguration) `; currently importing this creates a circular reference (done in [PR #45617](https://github.com/kubernetes/kubernetes/pull/45617))
- [x] ~~Review package structure in order to share among kubeadm init and kubeadm phase some utilities e.g.  `func (results BulkCreateCertResult) String() string`;~~ (does not apply anymore)
- [x] ~~Review and complete support for --config~~ (each phase will implement --config support)
- [x] ~~Review priority for settings flags: command line flags > config file > ENV vars > defaults~~ (currently config file | command line flags > defaults; ENV vars does not apply anymore)
- [x] ~~Fix behaviour of parameters insensible to KUBE_KUBERNETES_DIR env var~~ ( KUBE_KUBERNETES_DIR is now a constant)
  - ~~CertificatesDir defaults to /etc/kubernetes/pk~~
  - ~~CACertPath  defaults to "/etc/kubernetes/pki/ca.crt"~~ 
- [ ] ~~Review validation and defaulting of parameters currently handled only the UX, and thus exposing direct calls to phases to unexpected behaviour (to be confirmed)~~

Extending Support & Documentation:
- [ ] TBD

Contentious:
- [x] ~~Use verb/nouns for each phase naming e.g. certs -> init-certs or create-certs~~ (going on with current approach)
- [ ] ~~Improve code completion experience with numbered aliases (to be confirmed)~~

**Comment by fabriziopandini** [comment]
Create PR [Implementing phases in kubeadm - step 1: phase certs #45617](https://github.com/kubernetes/kubernetes/pull/45617)

**Comment by fabriziopandini** [comment]
Verifying if (fix cert dir in kubeadm #45008)[https://github.com/kubernetes/kubernetes/pull/45008 address] addresses "Fix behaviour of parameters insensible to KUBE_KUBERNETES_DIR env var"

**Comment by fabriziopandini** [comment]
Follow discussion about [fix kubeadm args #43558](https://github.com/kubernetes/kubernetes/pull/43558); it could address or drop "Review priority for settings flags: command line flags > config file > ENV vars > defaults (to be confirmed)"

**Comment by luxas** [comment]
I'm gonna incorporate this into my proposal (#156) in the next coming days...
Thanks!

**Comment by gtirloni** [comment]
It'd be interesting for cfg mgmt tools if the pre-flight checks could also be initiated separately.

**Comment by luxas** [comment]
@gtirloni Sounds like a good improvement, can you spawn a separate issue for that?
Also, feel free to implement it ;)

**Comment by gtirloni** [comment]
Thanks for reviewing the idea. I'll try to learn more about the work that is being done with the phases and see if I can implement something without breaking the whole world :)

**Comment by fabriziopandini** [comment]
created [kubeadm: Implementing the kubeconfig phase fully #49419](https://github.com/kubernetes/kubernetes/issues/49419)

**Comment by fabriziopandini** [comment]
created [kubeadm: Implementing the controlplane phase #50302](https://github.com/kubernetes/kubernetes/issues/50302)

**Comment by luxas** [comment]
All desired phases are now implemented, yayy :tada:. Design doc coming in #424
