### ISSUE TITLE
1.29: housekeeping tasks

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubeadm#2910]
This is a tracking issue for tasks that we are required to carry out during each cycle. **It tracks the upcoming release of Kubernetes 1.29 (1.x)**

Note: make sure you reference this issue in PRs.
 
same issue for 1.x-1 (see example PRs): #2857

 _When 1.x-4 version goes out of support_ https://kubernetes.io/releases/#release-history
 
* [x]   Drop kinder support for 1.x-4 and older (may not be needed every release)
[there are some TODOs for 1.25](https://github.com/search?q=repo%3Akubernetes%2Fkubeadm%201.25&type=code)\
- https://github.com/kubernetes/kubeadm/pull/2966

* [x]   Vendor the latest system-validators in kubernetes/kubernetes (may not be needed every release)
* [x]   Cleanup E2E jobs for 1.x-4 (requires two PRs)
  set `KUBERNETES_VERSION` to 1.x-1 and `KUBERNETES_SKEW` to `3` in /kinder/hack/update-workflows.sh
  make sure `PATH_TEST_INFRA` points to the right path.
  run the script and send two PRs for k/kubeadm and k/test-infra.
  See [KEP-3935: Generate test configurations for n-3 node skew #2855](https://github.com/kubernetes/kubeadm/pull/2855)

 _When the release-1.x branch and release-1.x test dashboards are created_
* [x]   Create E2E jobs for 1.x
  set `KUBERNETES_VERSION` to 1.x and `KUBERNETES_SKEW` to `3` in /kinder/hack/update-workflows.sh
  make sure `PATH_TEST_INFRA` points to the right path.
  run the script and send two PRs for k/kubeadm and k/test-infra.

- https://github.com/kubernetes/test-infra/pull/31194
- https://github.com/kubernetes/kubeadm/pull/2956

_Before the 1.x+1 cycle start_

* [ ]   Duplicate this issue for tracking 1.x+1 housekeeping tasks
* [ ]   Close this issue

**Comment by neolit123** [comment]
/assign

the release-1.29 branch creation is scheduled for 1.29.

**Comment by liangyuanpeng** [comment]
I' m come back after code freeze for 1.29 and still want to try it.
I cane see the below task need to work for 1.29:

- Update github action workflow for 1.29, same with https://github.com/kubernetes/kubeadm/pull/2855
- Update test-infra for KEP-3935, same with: https://github.com/kubernetes/test-infra/pull/29287
- Add test github workflow for 1.29, same with https://github.com/kubernetes/kubeadm/pull/2906

I'm looking forward to knowing if I can try it out and some guidance on that,Thanks :)

@neolit123

**Comment by chendave** [comment]
@liangyuanpeng feel free to go, there is a script(/kinder/hack/update-workflows.sh) can generate those change I believe, so it's pretty lightweight change I think.

**Comment by liangyuanpeng** [comment]
I have create a PR https://github.com/kubernetes/kubeadm/pull/2956 for it and i think have not script to generate files for kubernetes/test-infra side, right? Thanks.

**Comment by neolit123** [comment]
the new PRs seem fine but they must be on hold until 21s Nov

> _When the release-1.x branch and release-1.x test dashboards are created_

**Comment by neolit123** [comment]
1.30
https://github.com/kubernetes/kubeadm/issues/2982
