### ISSUE TITLE
1.30: housekeeping tasks

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2982]
This is a tracking issue for tasks that we are required to carry out during each cycle. **It tracks the upcoming release of Kubernetes 1.30 (1.x)**

Note: make sure you reference this issue in PRs.
 
same issue for 1.x-1 (see example PRs): #2910

 _When 1.x-4 version goes out of support_ https://kubernetes.io/releases/#release-history
 
* [x]   Drop kinder support for 1.x-4 and older (may not be needed every release)
* [x]   Vendor the latest system-validators in kubernetes/kubernetes (may not be needed every release)
* [x]   Cleanup E2E jobs for 1.x-4 (requires two PRs)
  set `KUBERNETES_VERSION` to 1.x-1 and `KUBERNETES_SKEW` to `3` in /kinder/hack/update-workflows.sh
  make sure `PATH_TEST_INFRA` points to the right path.
  run the script and send two PRs for k/kubeadm and k/test-infra.
  See [KEP-3935: Generate test configurations for n-3 node skew #2855](https://github.com/kubernetes/kubeadm/pull/2855)

 _When the release-1.x branch and release-1.x test dashboards are created_
* [x]   Create E2E jobs for 1.x
  set `KUBERNETES_VERSION` to 1.x and `KUBERNETES_SKEW` to `3` in /kinder/hack/update-workflows.sh
  make sure `PATH_TEST_INFRA` points to the right path.
  run the script and send two PRs for k/kubeadm and k/test-infra.

_Before the 1.x+1 cycle start_

* [x]   Duplicate this issue for tracking 1.x+1 housekeeping tasks
* [x]   Close this issue

**Comment by peizhouyu** [comment]
I want to try , reference v1.29

/assign

**Comment by neolit123** [comment]
folks, please look at this sentence:
> When the release-1.x branch and release-1.x test dashboards are created

it will happen around march 2024, not now.

**Comment by peizhouyu** [comment]
> folks, please look at this sentence:
> 
> > When the release-1.x branch and release-1.x test dashboards are created
> 
> it will happen around march 2024, not now.

Thanks for reply, I'll start at a better time 😅
