### ISSUE TITLE
1.32: housekeeping tasks

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#3097]
This is a tracking issue for tasks that we are required to carry out during each cycle. **It tracks the upcoming release of Kubernetes 1.32 (1.x)**

Note: make sure you reference this issue in PRs.
 
same issue for 1.x-1 (see example PRs): #3047

 _When 1.x-4 version goes out of support_ https://kubernetes.io/releases/#release-history
 
* [x]   Drop kinder support for 1.x-4 and older (may not be needed every release)
* [x]   Vendor the latest system-validators in kubernetes/kubernetes (may not be needed every release)
  * https://github.com/kubernetes/system-validators/pull/38
  * https://github.com/kubernetes/system-validators/pull/37
  * https://github.com/kubernetes/system-validators/pull/40
  * https://github.com/kubernetes/kubernetes/pull/128533

_Before docs freeze_
* [x] Submit PRs for kubernetes/website `dev-1.x` branch to update the documentation
  * https://github.com/kubernetes/website/pull/48408

 _When the release-1.x branch and release-1.x test dashboards are created_
* [x]   Create E2E jobs for 1.x
  set `KUBERNETES_VERSION` to 1.x in /kinder/hack/update-workflows.sh
  make sure `PATH_TEST_INFRA` points to the right path.
  run the script and send two PRs for k/kubeadm and k/test-infra.
  * https://github.com/kubernetes/test-infra/pull/33892
  * https://github.com/kubernetes/kubeadm/pull/3130

_Before the 1.x+1 cycle start_
* [x]   Duplicate this issue for tracking 1.x+1 housekeeping tasks
* [x]   Close this issue

**Comment by neolit123** [comment]
1.33
- https://github.com/kubernetes/kubeadm/issues/3135
