### ISSUE TITLE
Cherrypicking tracker issue for v1.9

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#626]
This issue serves as an umbrella to track the kubeadm-related PRs we cherrypick into the v1.9 branch.

I've been a cherrypick lead for the kubeadm releases so far, but didn't come up with the idea to track things in a centralized manner like this before ¯\_(ツ)_/¯

I propose that @timothysc function as the cherrypick lead on the kubeadm side for v1.9

I've identified a list of PRs to be cherrypicked:

 - [x] CoreDNS update to 1.0.1: https://github.com/kubernetes/kubernetes/pull/57296
    - @xiangpengzhao please cherrypick this PR to v1.9
 - [x] Bump etcd version to 3.1.11: https://github.com/kubernetes/kubernetes/pull/57238
    - Action needed: kubeadm should bump the etcd version used on the v1.9 branch to 3.1.11 at HEAD now and backport to v1.9 ASAP. @xiangpengzhao maybe can help with such a PR
 - [x] Only fail preflight checks on known manifests: https://github.com/kubernetes/kubernetes/pull/57287
   - @mattkelly please let us know if you need help with cherrypicking this PR

Individual cherrypick PRs should be created as documented here: https://github.com/kubernetes/community/blob/master/contributors/devel/cherry-picks.md

TL;DR; download https://github.com/github/hub, make sure `git remote -v` looks something like this and execute:

```bash
$ git remote -v
origin	git@github.com:luxas/kubernetes.git (fetch)
origin	git@github.com:luxas/kubernetes.git (push)
upstream	https://github.com/kubernetes/kubernetes (fetch)
upstream	DISABLE (push)

# Example command
GITHUB_USER=luxas hack/cherry_pick_pull.sh upstream/release-1.9 57296
```

The script will do everything for you, including creating the PR. You only need to get approval from @timothysc / me as kubeadm approvers and @mbohlool that is [the v1.9 patch manager](https://github.com/kubernetes/features/blob/master/release-1.9/release_team.md) and then the cherrypick can be merged!

**Comment by xiangpengzhao** [comment]
Oh! I was thinking of cherry-picking https://github.com/kubernetes/kubernetes/pull/57296 when it was lgtm'd but I forgot it after it got merged. :sweat_smile: 

cherry-pick PRs sent:
https://github.com/kubernetes/kubernetes/pull/57632
https://github.com/kubernetes/kubernetes/pull/57633

**Comment by mattkelly** [comment]
Here you go: https://github.com/kubernetes/kubernetes/pull/57635. Just let me know if I need to fix anything up!

**Comment by timothysc** [comment]
From what I can tell all the above PR's have been cherry-picked.

**Comment by xiangpengzhao** [comment]
https://github.com/kubernetes/kubernetes/pull/57811 (Update etcd version to 3.1.11 for release 1.9) instead of https://github.com/kubernetes/kubernetes/pull/57633

**Comment by timothysc** [comment]
I'm going to close out this issue now, as it's past it's lifetime.
