### ISSUE TITLE
kubeadm graduation requirements

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#63]
_From @mikedanese on August 30, 2016 16:33_

We need to decide on a scope for kubeadm that we feel comfortable strapping a `beta` label onto.

Beta requirements:
- [x] TLS bootstrap in beta https://github.com/kubernetes/features/issues/43
- [ ] Discovery API in beta #31779
- [x] e2e testing

Beta or GA?
- [ ] CA certificate rotation
- [x] join secret rotation

GA requirements:
- [ ] TLS bootstrap GA
- [ ] Discovery API GA

Wishlist:
- [ ] Better support for self hosting
  - [ ] Kubelet checkpointing
- [ ] High availability
- [ ] Kubeconfig v2

@kubernetes/sig-cluster-lifecycle 

_Copied from original issue: kubernetes/kubernetes#31711_

**Comment by mikedanese** [comment]
_From @lukemarsden on August 30, 2016 17:7_

Thanks for this!

I think it might make sense to distinguish between items such as "phase I => beta" or "phase II => alpha", according to the phase I/II breakdown in https://github.com/kubernetes/kubernetes/pull/30360 ([here](https://github.com/lukemarsden/kubernetes/blob/a692dea1c9be15bf34194fbab81519058fdf19f4/docs/proposals/dramatically-simplify-cluster-creation.md#user-stories) to save you some clicks)

**Comment by mikedanese** [comment]
_From @philips on September 9, 2016 16:22_

@mikedanese Sorry to be annoying, but could we use a feature for this? https://github.com/kubernetes/features

**Comment by mikedanese** [comment]
_From @pires on October 5, 2016 9:59_

Was this even looked at during yesterday's meeting?

**Comment by mikedanese** [comment]
@pires I think we should discuss what beta means in more depth next meeting.

**Comment by mikedanese** [comment]
_From @pires on October 5, 2016 22:9_

@mikedanese agreed. Added item on meeting's agenda.

**Comment by mikedanese** [comment]
_From @pires on October 15, 2016 12:37_

We have agreed to have several `kubeadm` components with each having its own graduation requirements, right? E.g., `kubeadm` could be GA while `kubeadm HA` is alpha.

**Comment by mikedanese** [comment]
_From @pires on October 15, 2016 13:47_

@mikedanese we should add testing (#34136) as a hard requirement for GA.

**Comment by mikedanese** [comment]
Added to the beta graduation requirements,

**Comment by mikedanese** [comment]
_From @mcapuccini on November 20, 2016 15:44_

Hello! Is the HA support for kubeadm under development? Will it be in K8s 1.5?

**Comment by mikedanese** [comment]
_From @luxas on November 20, 2016 18:42_

HA for everyone is an extremely complicated task given Kubernetes' current architecture without having a cloud provider, central loadbalancer or something like that you can rely on, but eventually we'd like to have HA support for kubeadm, yes.

See the v1.6 objectives which includes steps to get closer to bare-metal HA: https://docs.google.com/document/d/1v4k7eN-eetHbbpTAG7WuioRAMsK_FVGi1yC3VIn4Inw/edit#heading=h.8dh1uxinqwag
We will probably not have full-blown HA support for v1.6.

**Comment by mikedanese** [comment]
_From @philips on November 22, 2016 19:34_

@luxas I think HA can be made easier if we fix the API server to advertise DNS instead of just an IP and fix the default "race" where two API servers just flip-flop forever.

**Comment by luxas** [comment]
I think we cover this in the features issues we've spawned, so this doesn't make as much sense anymore as it did early on. Closing...
