### ISSUE TITLE
Checklist for kubeadm join --control-plane implementation

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#751]
This is the checklist for the implementation of `kubeadm join --control-plane` [Kubernetes Enhancement Proposal](https://github.com/kubernetes/community/blob/master/keps/sig-cluster-lifecycle/draft-20180130-kubeadm-join-master.md#kubeadm-join---master-workflow).

A first prototype is [here](https://github.com/kubernetes/kubernetes/pull/58261), but the final implementation is expected to:
* take advantage of the `API.ControlPlaneEndpoint` introduced in v1.10 (see [here](https://github.com/kubernetes/kubeadm/issues/726)) 
* remove/simplify as much as possible preconditions/limitations defined in the proposal (see [here](https://github.com/kubernetes/community/blob/master/keps/sig-cluster-lifecycle/draft-20180130-kubeadm-join-master.md#user-stories)).
* simplify as much as possible the UX

The implementation is going to be done through a set of PRs; any contribution is always well accepted!

- [x] ** DONE update the KEP
- [x] ** DONE https://github.com/kubernetes/website/pull/8301 ** Adds a task for HA etcd kubeadm (document how to create an external etcd with phases)
- [x] ** DONE https://github.com/kubernetes/kubernetes/pull/62947 ** make `API.ControlPlaneEndpoint` accept IP and DNS
- [x] ** DONE https://github.com/kubernetes/kubernetes/pull/62948 ** make kubeadm phases ready for join master
- [x] ** DONE https://github.com/kubernetes/kubernetes/pull/66873 ** implement the `kubeadm join --control-plane` main workflow 
- [x] define a MVP test plan for HA control plane.
- [x] ** IN PROGRESS  https://github.com/kubernetes/kubernetes/pull/66973** implement upgradability for HA (depends on [this](https://github.com/kubernetes/community/pull/1915))
- [x] ** ISSUE [1058](https://github.com/kubernetes/kubeadm/issues/1058) / PR https://github.com/kubernetes/kubernetes/pull/67786 / ISSUE https://github.com/kubernetes/kubeadm/issues/1072** remove (or deprecate) --feature-gates=HighAvailability, --feature-gates=SelfHosting, --feature-gates=CertsInSecrets
- [ ] implement the `kubeadm join --control-plane` secondary workflows (TBD)
- [ ] documentation for the public web site
- [ ] bootstrap a new etcd member with the kubeadm join --control-plane scenario as well.

**Comment by neolit123** [comment]
@fabriziopandini 

hi,
>  remove --feature-gates=HighAvailability

would this mean to simply ignore the FG in the case of `kubeadm join --master` or remove it from the code base completely:
https://github.com/kubernetes/kubernetes/search?utf8=%E2%9C%93&q=HighAvailability&type=

**Comment by chulkilee** [comment]
BTW https://github.com/kubernetes/website/pull/8301 should be mentioned too

**Comment by fabriziopandini** [comment]
@neolit123 
if I'm right, the Lease Endpoint reconciler will be the default reconciler in v1.11

If this is true IMO we can remove this feature gates-from the code, having care to provide a safe path for upgrading clusters now using this flag (e.g. by implementing a mutation of the kubeadm configmap that removes this flag when updating).

@luxas, @timothysc could you confirm the Lease reconciler will be default in v1.11 ? WDYT of the proposed solutions ?

**Comment by timothysc** [comment]
/assign @chuckha  

Once the HA doc references we can close this issue.

**Comment by timothysc** [comment]
I'm actually going to close this in favor of #1044 doc update as the last step.

**Comment by fabriziopandini** [comment]
Thanks @timothysc . it was on my list to update this tracking issue (done) and close in favour of more actionable tickets; added https://github.com/kubernetes/kubeadm/issues/1123 as well
