### ISSUE TITLE
document "CoreDNS by default in v1.11"

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#843]
this PR set the feature gate for CoreDNS to true by default:
https://github.com/kubernetes/kubernetes/pull/63509

feature discussion:
https://github.com/kubernetes/features/issues/427

document the transition in the docs (mentioned in a lot of places).

**task list:**
- [x] https://kubernetes.io/docs/tasks/administer-cluster/coredns/

**---> PR** sent and amended multiple times.
https://github.com/kubernetes/website/pull/8697

- [x] https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/

**---> PR**
https://github.com/kubernetes/website/pull/8728

- [x] https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-alpha/#cmd-phase-addon

**---> PR** https://github.com/kubernetes/website/pull/8727

- [x] https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/
- [x] https://kubernetes.io/docs/setup/independent/troubleshooting-kubeadm.md

**---> PR**
https://github.com/kubernetes/website/pull/8753

- [x] https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/

discussion / proposal for changes:
https://docs.google.com/document/d/1RFAN8e0q_Zfyyz9ZYGB6m-vaArgAZsnrsbv8BaQdH8o/edit?usp=sharing

**---> PR**
https://github.com/kubernetes/website/pull/8900

- [x] https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/

**---> PR**
https://github.com/kubernetes/website/pull/8829

`Kubernetes Features OSS tracking board (1.11 release)`:
https://docs.google.com/spreadsheets/d/16N9KSlxWwxUA2gV6jvuW9N8tPRHzNhu1-RYY4Y0RZLs/edit#gid=0

----

we are **not** touching the following DNS related pages:
- [ ] https://kubernetes.io/docs/tasks/administer-cluster/dns-horizontal-autoscaling/
- [ ] https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/
- [ ] https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/
- [ ] https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/

if you think that we should do otherwise, do tell.

**Comment by neolit123** [comment]
on the call today i've made the estimate that there are 20 website pages to update for this.
that was a bit off, sorry.

me and @detiber found these:
https://kubernetes.io/docs/tasks/administer-cluster/coredns/
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-alpha/#cmd-phase-addon
https://kubernetes.io/docs/tasks/administer-cluster/upgrade-downgrade/kubeadm-upgrade-1-9/
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/
https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/
https://kubernetes.io/docs/tasks/administer-cluster/dns-horizontal-autoscaling/
https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/
https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

i haven't verified all so we can pass on updating some of them, too.

**Comment by neolit123** [comment]
i was instructed to break this into separate PRs against `website`, which will complicate things a bit.
@luxas, @timothysc, @detiber, i will bump this space when a new change is made so that you can quickly comment / approve to get the process going.

first one:
kubernetes/website#8697

**Comment by johnbelamaric** [comment]
cc @rajansandeep

**Comment by rajansandeep** [comment]
@neolit123 Is it ok if I can help out with the documentation?

**Comment by neolit123** [comment]
@rajansandeep that would be much appreciated. thank you.

can you please verify that the non-kubeadm links above need any updates?
we kind of searched for "dns" and ended up with that list.

**Comment by rajansandeep** [comment]
@neolit123 Sure. I'll check.
There will be a separate PR for each link?

**Comment by neolit123** [comment]
@rajansandeep 

so the kubeadm related changes are mostly submitted as PRs now (list in first post).

i'm not sure you had a look at what has to be changed here:
https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/

i've created a google docs file to allow us to discuss this:
https://docs.google.com/document/d/1RFAN8e0q_Zfyyz9ZYGB6m-vaArgAZsnrsbv8BaQdH8o/edit?usp=sharing

please, have a look at my comments there and let's talk about this.
