### ISSUE TITLE
Tracking issue for "Config to v1beta1"

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#963]
Tracking issue for `v1beta1` related tasks.

1.12 planning doc:
https://docs.google.com/document/d/1YP8sCtgo58yqQ9sR4nsn9iuVFmglCCBMivCTwjd1ERE/edit#

- [x] Write a KEP for the v1beta1 config API
@fabriziopandini @luxas 
https://github.com/kubernetes/community/pull/2451
Based on gdocs proposal draft here: https://docs.google.com/document/d/1Sk2VW7IKaLjrjf_4a1NEU0l7X0ysZoXq9lVBvH-ruYY/edit#heading=h.jt5lxzh770he 
related: https://github.com/kubernetes/kubeadm/issues/911

- [x] Remove v1alpha1
@luxas 
https://github.com/kubernetes/kubernetes/pull/65628 and https://github.com/kubernetes/kubernetes/pull/65776

- [x] Create new v1alpha3 API
@luxas 
We will rename to `v1beta1` at the end of the v1.12 cycle if we’re confident in it
https://github.com/kubernetes/kubernetes/pull/65629

- [x] Move ComponentConfigs out to different YAML documents 
  - [x] Add support for kubeadm reading multiple YAML documents
@luxas
https://github.com/kubernetes/kubernetes/pull/65631
  - [x] Start using internal versions for ComponentConfigs in the internal API
@luxas
https://github.com/kubernetes/kubernetes/pull/65940
  - [x] Use separate YAML docs for the kubelet and kube-proxy ComponentConfigs
@luxas
https://github.com/kubernetes/kubernetes/pull/65787
  - [ ] Add support for `kubeadm config print-defaults --componentConfig` 
https://github.com/kubernetes/kubeadm/issues/1126
  - [x] Change authoritative source for component config
Don't upload the extra ComponentConfig YAML documents to the cluster configmap and on upgrade, fetch the components' ConfigMaps back 
@fabriziopandini
https://github.com/kubernetes/kubernetes/pull/67944

- [ ] Split cluster specification from runtime variables
  - [x] `MasterConfiguration` to `InitConfiguration` 
@luxas
https://github.com/kubernetes/kubernetes/pull/65945
  - [x] `NodeConfiguration` to `JoinConfiguration` 
@luxas >> @fabriziopandini
https://github.com/kubernetes/kubernetes/pull/65951
  - [x] Make the kubeadm config kinds mutually exclusive 
@luxas >> @fabriziopandini
https://github.com/kubernetes/kubernetes/pull/65952
  - [ ] Cleanup `util/config/*`; filename and methods should be updated to use new names
https://github.com/kubernetes/kubeadm/issues/1125
  - [x] Split `InitConfiguration` and `ClusterConfiguration`
and Don't upload the extra `InitConfiguration` to the cluster configmap
 @luxas 
https://github.com/kubernetes/kubernetes/pull/66219 (HOLD)
 @rosti 
https://github.com/kubernetes/kubernetes/pull/67441
https://github.com/kubernetes/kubernetes/pull/67503
further cleanups --> ISSUE https://github.com/kubernetes/kubeadm/issues/1084

- [x] Improve node/kubelet configuration by using substructs
Already done in v1alpha2
  - [x] Change authoritative source for node/kubelet by reading nodeName/cri info etc from the node when necessary (e.g. update, reset)
@fabriziopandini
https://github.com/kubernetes/kubernetes/pull/67944

- [ ] Improve controlplane configuration by using substructs

- [x] Improve Etcd configuration by using substructs
Already done in v1alpha2

- [x] Improve bootstrap token configuration by using substructs
Already done in v1alpha2

- [x] Introduce support for clusters with n>1 controlplane instances
@fabriziopandini
https://github.com/kubernetes/kubernetes/pull/67830
https://github.com/kubernetes/kubernetes/pull/67832

- [ ] Addons configuration
    relevant issues:
    - Improvements to the handling of cluster addons https://github.com/kubernetes/kubeadm/issues/1091
    - Allow overriding CoreDNS image https://github.com/kubernetes/kubeadm/issues/1017
    - Make the kube-proxy ComponentConfig `v1beta1` https://github.com/kubernetes/kubeadm/issues/967

- [ ] Refactor the Discovery joining API types

- [x] ~~Rationalize with Cluster API~~

- [ ] Make flags override config values e.g. - NodeName override.
   relevant issues:
    - Develop a unified policy for command like flags vs config file options https://github.com/kubernetes/kubeadm/issues/1040  

- [ ] etcd HA capabilities 
     - Introduce a StackedEtcd type 
https://github.com/kubernetes/kubeadm/issues/1123

- [x] Nix self hosting.
    relevant issues:
    - Remove (or deprecate) --feature-gates=HighAvailability, SelfHosting, CertsInSecrets https://github.com/kubernetes/kubeadm/issues/1058    
https://github.com/kubernetes/kubernetes/pull/67786
https://github.com/kubernetes/kubeadm/issues/1072

- [ ] The BootstrapTokenString object should move out to either k8s.io/client-go or k8s.io/api 
    relevant issues:
    - https://github.com/kubernetes/kubernetes/pull/67356

**Comment by fabriziopandini** [comment]
@timothysc @neolit123 
I propose to close this one.
All the open points are tracked into separated, more actionable tickets, with exception of two points where I'm not sure if there is consensus or not, which are tracked on the original umbrella issue #911
WDYT?

**Comment by neolit123** [comment]
> All the open points are tracked into separated, more actionable tickets, with exception of two points where I'm not sure if there is consensus or not, which are tracked on the original umbrella issue #911

+1
tracking issues should contain a smaller number of items, ideally.

**Comment by fabriziopandini** [comment]
closing with lazy consensus 😉
